# Uncomment this line to define a global platform for your project

platform :ios, '8.0'

target 'FBMessengerShareLocation' do

pod 'FBSDKLoginKit'
pod 'FBSDKCoreKit'
pod 'FBSDKMessengerShareKit'
end

target 'FBMessengerShareLocationTests' do

end

